
[api]
  enabled = true
  port = 54321
  schemas = ["public", "graphql_public"]
  extra_search_path = ["public", "extensions"]
  max_rows = 1000

[auth]
  enable_signup = true

[auth.email]
  enable_signup = true
  double_confirm_changes = true

[db]
  port = 54322
  shadow_port = 54320
  major_version = 15

[studio]
  port = 54323

[storage]
  file_size_limit = "50MiB"

[functions.vietnamese-data-sync]
  verify_jwt = true
  import_map = "supabase/functions/import_map.json"

[functions.bank-rate-updater]
  verify_jwt = true
  import_map = "supabase/functions/import_map.json"

[functions.notification-sender]
  verify_jwt = true
  import_map = "supabase/functions/import_map.json"
